# Variables
$currentDate = Get-Date -Format "yyyy-MM-dd-HH-mm"
$exportPath = 'RawExport-' + $currentDate + '.json'

#Import-Module AzSentinel

$headers = New-Object "System.Collections.Generic.Dictionary[[String],[String]]"
#$headers.Add("Authorization", "Bearer eyJ0eXAiOiJKV1QiLCJhbGciOiJSUzI1NiIsIng1dCI6IjVCM25SeHRRN2ppOGVORGMzRnkwNUtmOTdaRSIsImtpZCI6IjVCM25SeHRRN2ppOGVORGMzRnkwNUtmOTdaRSJ9.eyJhdWQiOiJodHRwczovL21hbmFnZW1lbnQuY29yZS53aW5kb3dzLm5ldCIsImlzcyI6Imh0dHBzOi8vc3RzLndpbmRvd3MubmV0LzAwNTJhZDMzLTI5YjctNGVkYS05N2Q5LTEyMmQ1ZmYzODU5MC8iLCJpYXQiOjE3MDQzOTI2MTIsIm5iZiI6MTcwNDM5MjYxMiwiZXhwIjoxNzA0Mzk3MTg3LCJhY3IiOiIxIiwiYWlvIjoiQVZRQXEvOFZBQUFBM0hLZkxLRUhDMllpL29XTEJYdjZFVC9ncDFmRmRyUkZKSmFUT2dyclBZV2p4Yk9mc0hjaWdRVUhFdUw2NCszMTRZQjI2NXRMQ0Y2bmlkRnlVcmw2bFp6ODJ0Y3E5QWtFV21oSUFjUGQvMU09IiwiYW1yIjpbInB3ZCIsIm1mYSJdLCJhcHBpZCI6IjE4ZmJjYTE2LTIyMjQtNDVmNi04NWIwLWY3YmYyYjM5YjNmMyIsImFwcGlkYWNyIjoiMCIsImdyb3VwcyI6WyI3NmQzZmY1Mi1hMGNhLTQ1MzQtYTIxMi05ZGRmMGQ5MzhiMGYiLCI1YWMxMmQ2OS1iYTU2LTQ3ZTYtOWNkZC01YTk2M2VhZTA4MzMiLCI4NGEyMzg3YS00MGUzLTQxN2ItYmRmYi1kNTRiOGUxZDRhZTAiLCIwMDJjOTdlNy1lMmMxLTQ1MTAtYmNiNS1jYjkwZjc2NjNlZDEiLCJiYzNiNjhmYi05N2E0LTQ0OTAtYTljMS0yODkwZjYxZTk0NWQiXSwiaWR0eXAiOiJ1c2VyIiwiaXBhZGRyIjoiMTQyLjExNC41OS44MyIsIm5hbWUiOiJSaXhvbiBQb2x2aSIsIm9pZCI6ImM1MjA5MDhiLWVlOTctNDZmMC04N2E5LWJlNDEwYTVjZTlkYyIsInB1aWQiOiIxMDAzMjAwMkIwNjcxRjVBIiwicmgiOiIwLkFWQUFNNjFTQUxjcDJrNlgyUkl0WF9PRmtFWklmM2tBdXRkUHVrUGF3ZmoyTUJPMkFEMC4iLCJzY3AiOiJ1c2VyX2ltcGVyc29uYXRpb24iLCJzdWIiOiIybnpaRnRfZkk4VzFLTnJiZXJHa09RZ1BhRWl0NUQyS3lKdjl5WldhVW8wIiwidGlkIjoiMDA1MmFkMzMtMjliNy00ZWRhLTk3ZDktMTIyZDVmZjM4NTkwIiwidW5pcXVlX25hbWUiOiJycG9sQFRFTFVTc2VjdXJpdHlEZXYub25taWNyb3NvZnQuY29tIiwidXBuIjoicnBvbEBURUxVU3NlY3VyaXR5RGV2Lm9ubWljcm9zb2Z0LmNvbSIsInV0aSI6ImlyQmY0M3FvWDB5c1I0UjVJb3p6QXciLCJ2ZXIiOiIxLjAiLCJ3aWRzIjpbImI3OWZiZjRkLTNlZjktNDY4OS04MTQzLTc2YjE5NGU4NTUwOSJdLCJ4bXNfY2FlIjoiMSIsInhtc190Y2R0IjoxNjM3MjYxMDI5fQ.dI0zLf6ORBOLZmKxncwnqo6vMecyJJfUHIW0ENdG6Yhttz_ianHtW5N-bNNqYleJhhTC_gMZqaPDIwrYmF8PSO5Mp48PPRoyfk-NCkWQ_fXsbZrBfUyg14NOQEmQUWpm5q8gP_9ww4b42ArbLb7HunVGkAqyi92RkrMeB8jbqqyhNy6frHqqSWqmBpvHU-02iBzIztgpCPUgg_j60zDST7lgv0skJynX0RAb-bvjeSVAhuXV03dU4aY2GaXthQ9SWcWrpaBlciTn1i6_xx-_kHfN6j8P5rNHM5PvegdgPFiO_aPy3htECA01JhAeLtCeVOVzIrEzxTUvVkt724W80Q")

$response = Invoke-RestMethod 'https://management.azure.com/subscriptions/26613501-ed23-4f10-8aed-bd633914579d/resourceGroups/sales-rg/providers/Microsoft.OperationalInsights/workspaces/salesla/providers/Microsoft.SecurityInsights/alertRules?api-version=2023-02-01' -Method 'GET' -Headers $headers
$response | ConvertTo-Json -Depth 100 | Set-Content -Path $exportPath 






#Export-AzSentinel -workspace $workspaceName -Outputfolder ".\" -Kind Alert -TemplatesKind "Scheduled,MicrosoftSecurityIncidentCreation"

#Get-ChildItem -Filter "Alert*" -File | Rename-Item -NewName $exportPath 















# Set the subscription context
#Set-AzContext -SubscriptionId $subscriptionId

# Get the list of Azure Sentinel analytic rules
#$rules = Get-AzSentinelAlertRule -ResourceGroupName $resourceGroupName -WorkspaceName $workspaceName -SubscriptionId $subscriptionId

# Export the rules to a JSON file
#$rules | ConvertTo-Json | Out-File -FilePath $ruleExportPath

# Output the total number of rules extracted
#Write-Host "Total rules extracted: $($rules.Count)"