name: Export Sentinel analytic rules from tenant

on:
  workflow_dispatch: # Allows manual trigger

permissions:
  contents: write
  pull-requests: write

#defaults:
#  shell: pwsh

env:
  SUBSCRIPTION_ID: 26613501-ed23-4f10-8aed-bd633914579d
  RESOURCE_GROUP_NAME: 'sales-rg'
  WORKSPACE_NAME: 'salesla'
  WORKSPACE_ID: 1382c2fb-d2c0-4e6d-979b-e1e32d96190e
  GITHUB_CONTEXT: ${{ toJson(github) }} 
  WORKFLOW_ACTOR: ${{ toJson(github) }}.actor

jobs:
  export-rules:
    runs-on: windows-latest

    steps:
    - name: Show GitHub context
      shell: pwsh
      run: |
        echo "$GITHUB_CONTEXT"
        echo $GITHUB_CONTEXT.actor
        echo $WORKFLOW_ACTOR

    - name: Checkout repository
      uses: actions/checkout@v3
    
    - name: Login
      uses: azure/login@v1
      with:
        creds: ${{ secrets.AZURE_CREDENTIALS_SALESLA }}
        enable-AzPSSession: true

    - name: Install Az.SecurityInsights Module
      shell: pwsh
      run: |
        Install-Module -Name Az.SecurityInsights -Force -AllowClobber

    - name: Install AzSentinel Module
      shell: pwsh
      run: |
        Install-Module -Name AzSentinel -Force -AllowClobber

    - name: Run Export script
      shell: pwsh
      run: |
        $subscriptionId = $env:SUBSCRIPTION_ID
        $resourceGroupName = $env:RESOURCE_GROUP_NAME
        $workspaceName = $env:WORKSPACE_NAME
        & .github/workflows/scripts/extract-sentinel-rules.ps1
    
    - name: Commit and Push Changes
      shell: pwsh
      run: |
        & .github/workflows/scripts/commit-and-push.ps1