name: Export Sentinel analytic rules from tenant

on:
  workflow_dispatch: # Allows manual trigger
      
jobs:
  export-rules:
    runs-on: windows-latest
    env:
      rootDirectory: '${{ github.workspace }}'

    steps:
    - name: Checkout repository
      uses: actions/checkout@v4
    
    - name: Login
      uses: azure/login@v1
      with:
        creds: ${{ secrets.AZURE_CREDENTIALS_SALESLA }}
    
    - name: Run PS script
      shell: pwsh
      run: |
        & .github/workflows/scripts/extract-sentinel-rules.ps1
    
    - name: Commit and Push Changes
      run: |
        git config --global user.name 'RixonTelus'
        git config --global user.email 'rixon.polvi@telus.com'
        git add .

        # Check for unstaged changes
        git status

        if (git diff-index --quiet HEAD --) {
        Write-Host "No changes detected."
        } else {
        # Commit if there are changes
        $currentDate = Get-Date -Format "yyyy-MM-dd HH:mm"
        git commit -m "Extracted Rules - $currentDate"
        
        # Push the changes
        git push origin HEAD:$(git branch --show-current)
        Write-Host "Changes have been pushed."
        }