name: Extract from salesla

on:
  #schedule:
  #  - cron: '0 0 * * *' # Runs every day at midnight
  workflow_dispatch: # Allows manual trigger

jobs:
  extract-rules:
    runs-on: ubuntu-latest
    env:
        subscriptionId: 26613501-ed23-4f10-8aed-bd633914579d
        resourceGroupName: 'sales-rg'
        workspaceName: 'salesla'
        workspaceId: 1382c2fb-d2c0-4e6d-979b-e1e32d96190e
        ruleExportPath: '.\Newexport.json'
        #cloudEnv: 'AzureCloud'

    steps:
    - name: Check Out
      uses: actions/checkout@v3
        
    - name: Login Azure
      uses: azure/login@v1
      with:
          client-id: ${{ secrets.AZURE_CLIENT_ID }}
          tenant-id: ${{ secrets.AZURE_TENANT_ID }}
          subscription-id: ${{ secrets.AZURE_SUBSCRIPTION_ID }}

    # just test
    - name: Azure CLI script
      uses: azure/CLI@v1
      with:
          azcliversion: latest
          inlineScript: |
            az account show

    # actual extraction
    - name: Run Azure PowerShell inline script
      uses: azure/powershell@v1
      with:
        inlineScript: |
          $rules = Get-AzSentinelAlertRule -WorkspaceName $workspaceName

          $rules | ConvertTo-Json | Out-File -FilePath $ruleExportPath

          Write-Host "Total rules extracted: $($rules.Count)"
        azPSVersion: "latest"
